### ISSUE TITLE
About Uncertainty

### ISSUE THREAD

**Issue by 22222222z** [Jun-CEN/Unified_Open_Set_Recognition#1]
Thank you for your open source work on this project.

I'm a little confused about how did you compute the uncertainty of a sample's prediction such as the Fig.3 in ur paper.
.

**Comment by Jun-CEN** [comment]
Uncertainty calculation methods are from existing open-set methods or OOD detection methods, like Maximum SoftMax Probability, ODIN, etc. Take the Maximum SoftMax Probability as an example. After we get the SoftMax probability vector of a sample, we pick up the highest probability p and use the 1-p as the uncertainty score.
